typography_spectrum: 0.9227498488035053
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#67686a'
    - '#342c22'
    - '#86c0ff'
  brandStrength: 0.875
  lightness: 0.04884804575704038
  saturation: 0
  rhythmicContrast: 0.7502979214768857
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.00051
analytics:
  google: null
  facebook: null
  twitter: null
name: Enja Design Service
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Enja Design Service
description: The Grid's still on Beta…
purpose: []
