name: Enja Design Service
favicon: null
layout_spectrum: 0.00051
typography_spectrum: 0.9227498488035053
title: Enja Design Service
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#67686a'
    - '#342c22'
    - '#86c0ff'
  brandStrength: 1
  lightness: 0.04884804575704038
  saturation: 0.6209604321047664
  rhythmicContrast: 0.7502979214768857
purpose: []
